Repository gacela-project/gacela, pull requests merged in 2021-03, with the labels that each got.

#3 Add tests missing factory & config
  tests/Fixtures/MissingConfigModule/MissingConfigModuleFacade.php
  tests/Fixtures/MissingConfigModule/MissingConfigModuleFactory.php
  tests/Fixtures/MissingFactoryModule/MissingFactoryModuleFacade.php
  tests/Integration/IntegrationTest.php
Labels: question

#2 Clean-up AbstractClassResolver
  src/ClassResolver/AbstractClassResolver.php
Labels: enhancement

#4 improves docs
  documentation/001_basic_concepts.md
  documentation/002_facade.md
  documentation/003_factory.md
  documentation/004_dependency_provider.md
  documentation/005_config.md
Labels: documentation

#5 Implementing a Locator to get the Facades from the DependencyProvider
  src/Container/Container.php
  src/Container/Locator.php
  tests/Fixtures/ExampleA/ExampleAFacade.php
  tests/Fixtures/ExampleA/ExampleAFacadeInterface.php
  tests/Fixtures/ExampleB/ExampleBDependencyProvider.php
  tests/Fixtures/ExampleB/ExampleBFacade.php
  tests/Fixtures/ExampleB/ExampleBFacadeInterface.php
  tests/Fixtures/ExampleC/ExampleCDependencyProvider.php
  tests/Fixtures/MissingConfigModule/MissingConfigModuleFacade.php
  tests/Fixtures/MissingConfigModule/MissingConfigModuleFactory.php
Labels: enhancement

#8 Refactoring ClassNameFinder
  src/AbstractFacade.php
  src/ClassResolver/AbstractClassResolver.php
  src/ClassResolver/ClassNameFinder/ClassNameFinder.php
  src/ClassResolver/ClassNameFinder/Rule/AbstractFinderRule.php
  src/ClassResolver/ClassNameFinder/Rule/FinderRuleInterface.php
  src/ClassResolver/ClassNameFinder/Rule/FinderRuleWithModulePrefix.php
  src/ClassResolver/ClassNameFinder/Rule/FinderRuleWithoutModulePrefix.php
  src/ClassResolver/ClassResolverExceptionTrait.php
  src/ClassResolver/Config/ConfigResolver.php
  src/ClassResolver/DependencyProvider/DependencyProviderResolver.php
  src/ClassResolver/Factory/FactoryResolver.php
  src/ClassResolver/Repository/RepositoryResolver.php
  src/Container/Locator.php
  tests/Fixtures/ExampleA/ExampleAFacadeInterface.php
  tests/Fixtures/ExampleA/Facade.php
  tests/Fixtures/ExampleA/FacadeInterface.php
  tests/Fixtures/ExampleA/Factory.php
  tests/Fixtures/ExampleA2/Config.php
  tests/Fixtures/ExampleA2/Facade.php
  tests/Fixtures/ExampleA2/Factory.php
  tests/Fixtures/ExampleA2/Service/ServiceA.php
  tests/Fixtures/ExampleB/DependencyProvider.php
  tests/Fixtures/ExampleB/ExampleBConfig.php
  tests/Fixtures/ExampleB/Facade.php
  tests/Fixtures/ExampleB/FacadeInterface.php
  tests/Fixtures/ExampleB/Factory.php
  tests/Fixtures/ExampleB/Service/ServiceB.php
  tests/Fixtures/ExampleC/DependencyProvider.php
  tests/Fixtures/ExampleC/Domain/Service/ServiceC.php
  tests/Fixtures/ExampleC/ExampleCFactory.php
  tests/Fixtures/ExampleC/ExampleCRepositoryInterface.php
  tests/Fixtures/ExampleC/ExampleD/ExampleDConfig.php
  tests/Fixtures/ExampleC/ExampleD/ExampleDFacade.php
  tests/Fixtures/ExampleC/ExampleD/ExampleDFacadeInterface.php
  tests/Fixtures/ExampleC/ExampleD/ExampleDFactory.php
  tests/Fixtures/ExampleC/ExampleD/Service/ServiceD.php
  tests/Fixtures/ExampleC/Facade.php
  tests/Fixtures/ExampleC/FacadeInterface.php
  tests/Fixtures/ExampleC/Factory.php
  tests/Fixtures/ExampleC/Infrastructure/Config.php
  tests/Fixtures/ExampleC/Infrastructure/Persistence/Repository.php
  tests/Fixtures/ExampleC/Infrastructure/Persistence/RepositoryInterface.php
  tests/Integration/IntegrationTest.php
Labels: refactoring

#10 Add config_local
  .gitignore
  documentation/004_config.md
  src/Config.php
  tests/Integration/UsingConfig/IntegrationTest.php
  tests/Integration/UsingConfig/LocalConfig/Config.php
  tests/Integration/UsingConfig/LocalConfig/Facade.php
  tests/Integration/UsingConfig/LocalConfig/Factory.php
  tests/Integration/UsingConfig/SimpleModule/Config.php
  tests/Integration/UsingConfig/config.php
  tests/Integration/UsingConfig/config_local.php
Labels: enhancement
