Repository gacela-project/gacela, pull requests merged in 2021-08, with the labels that each got.

#50 Infer the resolvedClass type when using addAnonymousGlobal()
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/GlobalKey.php
  src/Framework/ClassResolver/ResolvableType.php
  tests/Integration/Framework/GlobalServices/AnonymousClassesTest.php
  tests/Unit/Framework/ClassResolver/AbstractClassResolverTest.php
  tests/Unit/Framework/ClassResolver/GlobalKeyTest.php
  tests/Unit/Framework/ClassResolver/ResolvableTypeTest.php
Labels: refactoring

#52 Replace config file from json to php
  CHANGELOG.md
  src/Framework/Config.php
  src/Framework/Config/ConfigException.php
  src/Framework/Config/ConfigInit.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFileInterface.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigItemInterface.php
  src/Framework/Config/GacelaFileConfig/GacelaJsonConfigFile.php
  src/Framework/Config/GacelaFileConfig/GacelaJsonConfigItem.php
  src/Framework/Config/GacelaFileConfig/GacelaPhpConfigFile.php
  src/Framework/Config/GacelaFileConfig/GacelaPhpConfigItem.php
  src/Framework/Config/GacelaFileConfigFactoryInterface.php
  src/Framework/Config/GacelaJsonConfigFactory.php
  src/Framework/Config/GacelaJsonConfigFactoryInterface.php
  tests/Integration/Framework/UsingConfigWithoutGacelaFile/IntegrationTest.php
  tests/Integration/Framework/UsingConfigWithoutGacelaFile/LocalConfig/Config.php
  tests/Integration/Framework/UsingConfigWithoutGacelaFile/LocalConfig/Facade.php
  tests/Integration/Framework/UsingConfigWithoutGacelaFile/LocalConfig/Factory.php
  tests/Integration/Framework/UsingConfigWithoutGacelaFile/config/.env.omit
  tests/Integration/Framework/UsingConfigWithoutGacelaFile/config/default.php
  tests/Integration/Framework/UsingConfigWithoutGacelaFile/config/local.php
  tests/Integration/Framework/UsingConfigWithoutGacelaFile/config/omit.yml
  tests/Integration/Framework/UsingEnvConfig/gacela.json
  tests/Integration/Framework/UsingEnvConfig/gacela.php
  tests/Integration/Framework/UsingGacelaJson/IntegrationTest.php
  tests/Integration/Framework/UsingGacelaJson/LocalConfig/Config.php
  tests/Integration/Framework/UsingGacelaJson/LocalConfig/Facade.php
  tests/Integration/Framework/UsingGacelaJson/LocalConfig/Factory.php
  tests/Integration/Framework/UsingGacelaJson/config/default.php
  tests/Integration/Framework/UsingGacelaJson/config/local.php
  tests/Integration/Framework/UsingGacelaJson/gacela.json
  tests/Integration/Framework/UsingGacelaJsonMultiple/IntegrationTest.php
  tests/Integration/Framework/UsingGacelaJsonMultiple/LocalConfig/Config.php
  tests/Integration/Framework/UsingGacelaJsonMultiple/LocalConfig/Facade.php
  tests/Integration/Framework/UsingGacelaJsonMultiple/LocalConfig/Factory.php
  tests/Integration/Framework/UsingGacelaJsonMultiple/config/.env
  tests/Integration/Framework/UsingGacelaJsonMultiple/config/default.php
  tests/Integration/Framework/UsingGacelaJsonMultiple/gacela.json
  tests/Integration/Framework/UsingMultipleConfig/config/.env
  tests/Integration/Framework/UsingMultipleConfig/gacela.php
  tests/Integration/Framework/UsingPhpConfig/gacela.php
  tests/Unit/Framework/Config/ConfigInitTest.php
  tests/Unit/Framework/ConfigTest.php
Labels: enhancement, refactoring

#51 Class resolver with dependencies
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/DependencyResolver/DependencyResolver.php
  src/Framework/Config.php
  src/Framework/Config/ConfigFactory.php
  src/Framework/Config/ConfigInit.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/GacelaConfigFileFactoryInterface.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFileInterface.php
  src/Framework/Config/GacelaFileConfig/GacelaJsonConfigFile.php
  src/Framework/Config/GacelaFileConfig/GacelaPhpConfigFile.php
  src/Framework/Container/Locator.php
  src/Framework/Util/GlobalServices.php
  tests/Integration/Framework/UsingConfigDependencies/IntegrationTest.php
  tests/Integration/Framework/UsingConfigDependencies/LocalConfig/Domain/GreeterGeneratorInterface.php
  tests/Integration/Framework/UsingConfigDependencies/LocalConfig/Domain/NumberGeneratorInterface.php
  tests/Integration/Framework/UsingConfigDependencies/LocalConfig/Domain/NumberService.php
  tests/Integration/Framework/UsingConfigDependencies/LocalConfig/Facade.php
  tests/Integration/Framework/UsingConfigDependencies/LocalConfig/Factory.php
  tests/Integration/Framework/UsingConfigDependencies/LocalConfig/Infrastructure/CustomCompanyGenerator.php
  tests/Integration/Framework/UsingConfigDependencies/LocalConfig/Infrastructure/CustomNameGenerator.php
  tests/Integration/Framework/UsingConfigDependencies/gacela.php
  tests/Unit/Framework/ClassResolver/AbstractClassResolverTest.php
  tests/Unit/Framework/Config/ConfigInitTest.php
Labels: enhancement

#53 Refactor CodeGenerator module
  gacela
  src/CodeGenerator/CodeGeneratorConfig.php
  src/CodeGenerator/CodeGeneratorDependencyProvider.php
  src/CodeGenerator/CodeGeneratorFacade.php
  src/CodeGenerator/CodeGeneratorFactory.php
  src/CodeGenerator/Domain/CommandArguments/CommandArguments.php
  src/CodeGenerator/Domain/CommandArguments/CommandArgumentsException.php
  src/CodeGenerator/Domain/CommandArguments/CommandArgumentsParser.php
  src/CodeGenerator/Domain/CommandArguments/CommandArgumentsParserInterface.php
  src/CodeGenerator/Domain/FileContent/FileContentGenerator.php
  src/CodeGenerator/Domain/FileContent/FileContentGeneratorInterface.php
  src/CodeGenerator/Domain/FileContent/FileContentIoInterface.php
  src/CodeGenerator/Domain/FileContentGenerator.php
  src/CodeGenerator/Domain/FilenameSanitizer/FilenameSanitizer.php
  src/CodeGenerator/Domain/FilenameSanitizer/FilenameSanitizerInterface.php
  src/CodeGenerator/Infrastructure/Command/MakeFileCommand.php
  src/CodeGenerator/Infrastructure/Command/MakeModuleCommand.php
  src/CodeGenerator/Infrastructure/FileContentIo.php
  src/CodeGenerator/Infrastructure/Template/CodeTemplateInterface.php
  tests/Unit/CodeGenerator/Domain/CommandArguments/CommandArgumentsParserTest.php
  tests/Unit/CodeGenerator/Domain/FileContent/FileContentGeneratorTest.php
  tests/Unit/CodeGenerator/Domain/FilenameSanitizer/FilenameSanitizerTest.php
Labels: refactoring

#55 Some edge-cases in DependencyResolver
  CHANGELOG.md
  src/Framework/ClassResolver/DependencyResolver/DependencyResolver.php
  src/Framework/ClassResolver/DependencyResolver/DependencyResolverNotFoundException.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/IntegrationTest.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/NumberService.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvedClassInterface.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAbstractAnonClassCallable.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAbstractAnonClassFunction.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAnonClassCallableInterface.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAnonClassFunctionInterface.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Facade.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Factory.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Infrastructure/CorrectCompanyGenerator.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Infrastructure/CustomResolvedClass.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Infrastructure/IncorrectCompanyGenerator.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/gacela.php
  tests/Integration/Framework/UsingDeprecatedArrayConfig/LocalConfig/Factory.php
Labels: enhancement

#56 Increase PhpStan to max level
  phpstan.neon
  src/Framework/AbstractConfigGacela.php
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/ClassInfo.php
  src/Framework/ClassResolver/DependencyResolver/DependencyResolver.php
  src/Framework/Config.php
  src/Framework/Config/ConfigInit.php
  src/Framework/Config/ConfigReader/EnvConfigReader.php
  src/Framework/Config/ConfigReader/PhpConfigReader.php
  src/Framework/Config/ConfigReaderInterface.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigItem.php
  src/Framework/Config/PathFinder.php
  src/Framework/Config/PathFinderInterface.php
  src/Framework/Exception/Backtrace.php
Labels: enhancement

#58 Refactor tests related to binding interfaces
  .php-cs-fixer.dist.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/IntegrationTest.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/LocalConfig/Domain/AbstractClass.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/LocalConfig/Domain/AbstractFromAnonymousClass.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/LocalConfig/Domain/AbstractFromCallable.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/LocalConfig/Domain/InterfaceFromAnonymousClass.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/LocalConfig/Domain/InterfaceFromCallable.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/LocalConfig/Domain/Service.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/LocalConfig/Facade.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/LocalConfig/Factory.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/LocalConfig/Infrastructure/ConcreteClass.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/gacela.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/IntegrationTest.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Domain/GreeterGeneratorInterface.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Domain/NumberService.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Facade.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Factory.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Infrastructure/CorrectCompanyGenerator.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Infrastructure/CustomNameGenerator.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Infrastructure/IncorrectCompanyGenerator.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/gacela.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/IntegrationTest.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/NumberGeneratorInterface.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/NumberService.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvedClassInterface.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAbstractAnonClassCallable.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAbstractAnonClassFunction.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAnonClassCallableInterface.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAnonClassFunctionInterface.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Facade.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Factory.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Infrastructure/CustomNameGenerator.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Infrastructure/IncorrectCompanyGenerator.php
  tests/Integration/Framework/UsingConfigInterfacesMapping/gacela.php
Labels: refactoring, pure testing
