Repository gacela-project/gacela, pull requests merged in 2021-04, with the labels that each got.

#13 Implement CodeGenerator module
  composer.json
  gacela
  src/CodeGenerator/CodeGeneratorFacade.php
  src/CodeGenerator/CodeGeneratorFactory.php
  src/CodeGenerator/Domain/Command/AbstractMaker.php
  src/CodeGenerator/Domain/Command/ConfigMaker.php
  src/CodeGenerator/Domain/Command/DependencyProviderMaker.php
  src/CodeGenerator/Domain/Command/FacadeMaker.php
  src/CodeGenerator/Domain/Command/FactoryMaker.php
  src/CodeGenerator/Domain/Command/MakerInterface.php
  src/CodeGenerator/Domain/Command/ModuleMaker.php
  src/CodeGenerator/Domain/Io/MakerIoInterface.php
  src/CodeGenerator/Infrastructure/Io/SystemMakerIo.php
  tests/Integration/CodeGenerator/UsingIncorrectConfigurationTest.php
  tests/Integration/CodeGenerator/UsingMakeConfigTest.php
  tests/Integration/CodeGenerator/UsingMakeDependencyProviderTest.php
  tests/Integration/CodeGenerator/UsingMakeFacadeTest.php
  tests/Integration/CodeGenerator/UsingMakeFactoryTest.php
  tests/Integration/CodeGenerator/UsingMakeModuleTest.php
  tests/Integration/CodeGenerator/Util/DirectoryUtil.php
Labels: enhancement

#14 Create config directory
  src/Framework/Config.php
  tests/Integration/Framework/UsingConfig/config/default.php
  tests/Integration/Framework/UsingConfig/config/local.php
Labels: enhancement

#15 Update config documentation
  README.md
  docs/004_config.md
Labels: documentation

#17 Decouple the "maker templates" from the domain
  .gitignore
  src/CodeGenerator/CodeGeneratorConfig.php
  src/CodeGenerator/CodeGeneratorFacade.php
  src/CodeGenerator/CodeGeneratorFactory.php
  src/CodeGenerator/Domain/Command/AbstractMaker.php
  src/CodeGenerator/Domain/Command/ConfigMaker.php
  src/CodeGenerator/Domain/Command/DependencyProviderMaker.php
  src/CodeGenerator/Domain/Command/FacadeMaker.php
  src/CodeGenerator/Domain/Command/FactoryMaker.php
  src/CodeGenerator/Domain/Command/MakerInterface.php
  src/CodeGenerator/Domain/Command/ModuleMaker.php
  src/CodeGenerator/Domain/Io/CommandArgumentsParser.php
  src/CodeGenerator/Domain/ReadModel/CommandArguments.php
  src/CodeGenerator/Infrastructure/Template/Command/config-maker.txt
  src/CodeGenerator/Infrastructure/Template/Command/dependency-provider-maker.txt
  src/CodeGenerator/Infrastructure/Template/Command/facade-maker.txt
  src/CodeGenerator/Infrastructure/Template/Command/factory-maker.txt
Labels: refactoring

#19 Pass only one argument to the "maker command"
  .gitignore
  composer.json
  phpunit.xml
  src/CodeGenerator/CodeGeneratorConfig.php
  src/CodeGenerator/CodeGeneratorFactory.php
  src/CodeGenerator/Domain/Command/AbstractMaker.php
  src/CodeGenerator/Domain/Command/ModuleMaker.php
  src/CodeGenerator/Domain/Io/CommandArguments/CommandArgumentsParser.php
  src/CodeGenerator/Domain/Io/CommandArguments/Exception/CommandArgumentsException.php
  src/CodeGenerator/Domain/Io/CommandArgumentsParser.php
  src/CodeGenerator/Domain/ReadModel/CommandArguments.php
  tests/Integration/CodeGenerator/UsingIncorrectConfigurationTest.php
  tests/Integration/CodeGenerator/UsingMakeConfigTest.php
  tests/Integration/CodeGenerator/UsingMakeDependencyProviderTest.php
  tests/Integration/CodeGenerator/UsingMakeFacadeTest.php
  tests/Integration/CodeGenerator/UsingMakeFactoryTest.php
  tests/Integration/CodeGenerator/UsingMakeModuleTest.php
  tests/Integration/CodeGenerator/composer.json
  tests/Integration/Framework/UsingConfig/LocalConfig/Config.php
  tests/Unit/CodeGenerator/Io/CommandArguments/CommandArgumentsParserTest.php
Labels: enhancement

#18 Fixes documentation
  README.md
  docs/001_basic_concepts.md
  docs/002_facade.md
  docs/003_factory.md
  docs/004_config.md
  docs/005_dependency_provider.md
  docs/006_code_generator.md
  docs/README.md
  docs/imgs/gacela-logo.png
Labels: documentation

#20 Add LICENSE to the project
  LICENSE
  README.md
Labels: documentation

#21 Improve some config errors
  src/Framework/Config.php
Labels: enhancement
