Repository gacela-project/gacela, pull requests merged in 2021-07, with the labels that each got.

#32 Using long name by default in the generator code commands
  src/CodeGenerator/Domain/FileContentGenerator.php
  src/CodeGenerator/Infrastructure/Command/MakeFileCommand.php
  src/CodeGenerator/Infrastructure/Command/MakeModuleCommand.php
Labels: enhancement

#34 Add tests for CodeGenerator Domain layer
  src/CodeGenerator/CodeGeneratorFactory.php
  src/CodeGenerator/Domain/FileContentGenerator.php
  src/CodeGenerator/Infrastructure/FileContentIo.php
  src/CodeGenerator/Infrastructure/FileContentIoInterface.php
  tests/Unit/CodeGenerator/Domain/CommandArgumentsParserTest.php
  tests/Unit/CodeGenerator/Domain/FileContentGeneratorTest.php
  tests/Unit/CodeGenerator/Domain/FilenameSanitizerTest.php
Labels: pure testing

#33 Update csfixer rules to v.3
  .php-cs-fixer.dist.php
  .php_cs.dist
  composer.lock
  src/CodeGenerator/Domain/CommandArgumentsParser.php
  src/CodeGenerator/Domain/FilenameSanitizer.php
  src/Framework/AbstractConfig.php
  src/Framework/AbstractFacade.php
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/Config/ConfigResolver.php
  src/Framework/ClassResolver/DependencyProvider/DependencyProviderResolver.php
  src/Framework/ClassResolver/Factory/FactoryResolver.php
  src/Framework/Config.php
  src/Framework/ConfigResolverAwareTrait.php
  src/Framework/Container/Container.php
  src/Framework/Container/Locator.php
  src/Framework/Exception/Backtrace.php
  tests/Integration/Framework/UsingConfig/LocalConfig/Config.php
  tests/Unit/CodeGenerator/Domain/FilenameSanitizerTest.php
Labels: enhancement

#35 Allow using config php and env files
  docs/004_config.md
  src/Framework/Config.php
  src/Framework/Config/ConfigReaderInterface.php
  src/Framework/Config/EnvConfigReader.php
  src/Framework/Config/GacelaJsonConfig.php
  src/Framework/Config/PhpConfigReader.php
  src/Framework/Config/ReaderFactory.php
  tests/Integration/Framework/UsingConfig/config/subfolder/default.php
  tests/Integration/Framework/UsingEnvConfig/IntegrationTest.php
  tests/Integration/Framework/UsingEnvConfig/LocalConfig/Config.php
  tests/Integration/Framework/UsingEnvConfig/LocalConfig/Facade.php
  tests/Integration/Framework/UsingEnvConfig/LocalConfig/Factory.php
  tests/Integration/Framework/UsingEnvConfig/config/.env.dist
  tests/Integration/Framework/UsingEnvConfig/config/.env.local.dist
  tests/Integration/Framework/UsingEnvConfig/config/omit.php
  tests/Integration/Framework/UsingEnvConfig/config/omit.yml
  tests/Integration/Framework/UsingEnvConfig/gacela.json
  tests/Integration/Framework/UsingPhpConfig/IntegrationTest.php
  tests/Integration/Framework/UsingPhpConfig/LocalConfig/Config.php
  tests/Integration/Framework/UsingPhpConfig/LocalConfig/Facade.php
  tests/Integration/Framework/UsingPhpConfig/LocalConfig/Factory.php
  tests/Integration/Framework/UsingPhpConfig/config/.env.omit
  tests/Integration/Framework/UsingPhpConfig/config/default.php
  tests/Integration/Framework/UsingPhpConfig/config/local.php
  tests/Integration/Framework/UsingPhpConfig/config/omit.yml
  tests/Integration/Framework/UsingPhpConfig/gacela.json
Labels: enhancement

#36 AbstractClassResolver refactoring
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/ClassResolverExceptionTrait.php
  src/Framework/ClassResolver/Config/ConfigNotFoundException.php
  src/Framework/ClassResolver/Config/ConfigResolver.php
  src/Framework/ClassResolver/DependencyProvider/DependencyProviderNotFoundException.php
  src/Framework/ClassResolver/DependencyProvider/DependencyProviderResolver.php
  src/Framework/ClassResolver/Factory/FactoryNotFoundException.php
  src/Framework/ClassResolver/Factory/FactoryResolver.php
Labels: refactoring

#37 Simplify ClassNameFinder class
  src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/AbstractFinderRule.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleInterface.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithModulePrefix.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithoutModulePrefix.php
  src/Framework/Config/ReaderFactory.php
Labels: enhancement

#39 Adding unit tests to Container and Locator
  src/Framework/Container/Locator.php
  tests/Fixtures/StringValue.php
  tests/Fixtures/StringValueInterface.php
  tests/Unit/Framework/Container/ContainerTest.php
  tests/Unit/Framework/Container/LocatorTest.php
Labels: pure testing

#40 Refactor Config: extract ConfigInit logic
  src/Framework/Config.php
  src/Framework/Config/ConfigInit.php
  src/Framework/Config/ConfigReader/EnvConfigReader.php
  src/Framework/Config/ConfigReader/PhpConfigReader.php
  src/Framework/Config/GacelaJsonConfigFactory.php
  src/Framework/Config/GacelaJsonConfigFactoryInterface.php
  src/Framework/Config/PathFinder.php
  src/Framework/Config/PathFinderInterface.php
  tests/Unit/Framework/Config/ConfigReaderTest.php
Labels: refactoring

#44 Refactoring Config::setConfigReaders()
  src/CodeGenerator/CodeGeneratorConfig.php
  src/Framework/Config.php
  tests/Integration/Framework/UsingConfigWithoutGacelaJsonFile/IntegrationTest.php
  tests/Integration/Framework/UsingEnvConfig/IntegrationTest.php
  tests/Integration/Framework/UsingMultipleConfig/IntegrationTest.php
  tests/Integration/Framework/UsingPhpConfig/IntegrationTest.php
  tests/Unit/Framework/ConfigTest.php
Labels: enhancement

#43 Link the docs to the website
  README.md
  docs/001_basic_concepts.md
  docs/002_facade.md
  docs/003_factory.md
  docs/004_config.md
  docs/005_dependency_provider.md
  docs/006_code_generator.md
  docs/README.md
  gacela-logo.svg
Labels: documentation

#45 Fix PHP 8.0 bug for anonymous classes and added a matrix CI
  .github/workflows/ci.yml
  src/Framework/ClassResolver/ClassInfo.php
Labels: enhancement

#46 Anonymous classes are bind to a context
  CHANGELOG.md
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/ClassInfo.php
  tests/Benchmark/Framework/ClassResolver/AbstractFacadeBench.php
  tests/Integration/Framework/GlobalServices/AnonymousClassesTest.php
  tests/Integration/Framework/GlobalServices/GlobalServicesTest.php
  tests/Unit/Framework/ClassResolver/AbstractClassResolverTest.php
Labels: enhancement

#48 ConfigReaders will use config items from gacela
  CHANGELOG.md
  src/Framework/Config/ConfigException.php
  src/Framework/Config/ConfigInit.php
  src/Framework/Config/ConfigReaderException.php
  src/Framework/Config/GacelaJsonConfig.php
  src/Framework/Config/GacelaJsonConfigItem.php
  tests/Integration/Framework/UsingMultipleConfig/gacela.json
  tests/Unit/Framework/Config/ConfigInitTest.php
Labels: enhancement

#49 Fix bug in GlobalKey for Modules with multi names
  src/Framework/ClassResolver/GlobalKey.php
  tests/Unit/Framework/ClassResolver/AbstractClassResolverTest.php
  tests/Unit/Framework/ClassResolver/GlobalKeyTest.php
Labels: bug
