Repository gacela-project/gacela, pull requests merged in 2022-10, with the labels that each got.

#200 Full code coverage on Gacela/Console module
  src/Console/ConsoleConfig.php
  src/Console/Domain/ConsoleException.php
  src/Framework/Config/Config.php
  tests/Feature/CodeGenerator/MakeExceptionCommandTest.php
  tests/Feature/CodeGenerator/MakeFileCommandTest.php
  tests/Feature/CodeGenerator/MakeModuleCommandTest.php
  tests/Integration/Framework/Config/ConfigTest.php
Labels: refactoring

#204 Cache default resolved gacela class
  src/Framework/ClassResolver/AbstractClassResolver.php
Labels: enhancement

#205 Read autoload dev when parsing composer
  .gitignore
  CHANGELOG.md
  composer.json
  data/.gitkeep
  src/Console/Domain/CommandArguments/CommandArgumentsParser.php
  tests/Feature/CodeGenerator/MakeModuleCommandTest.php
  tests/Feature/CodeGenerator/composer.json
Labels: enhancement

#207 Group Cache and Profiler classes inside their folders
  src/Framework/ClassResolver/Cache/ClassNameCacheInterface.php
  src/Framework/ClassResolver/Cache/InMemoryClassNameCache.php
  src/Framework/ClassResolver/Cache/ProfiledInMemoryCache.php
  src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/ClassResolver/Profiler/AbstractJsonFileProfiler.php
  src/Framework/ClassResolver/Profiler/ClassNameJsonProfiler.php
  src/Framework/ClassResolver/Profiler/CustomServicesJsonProfiler.php
  src/Framework/ClassResolver/Profiler/FileProfilerInterface.php
  src/Framework/DocBlockResolver/DocBlockResolver.php
  src/Framework/Gacela.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/FileProfilerBench.php
  tests/Feature/Framework/CustomNoCacheDirectory/NoFileCacheFeatureTest.php
  tests/Feature/Framework/CustomProfilerDirectory/FileProfilerFeatureTest.php
  tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverCustomServicesAwareTest.php
  tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverInMemoryAwareTest.php
  tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
Labels: refactoring

#210 Normalize UseBlockParser
  src/Framework/ClassResolver/DocBlockService/UseBlockParser.php
  src/Framework/DocBlockResolver/DocBlockResolver.php
  tests/Unit/Framework/ClassResolver/DocBlockService/UseBlockParserTest.php
Labels: refactoring

#211 Add documentation to GacelaConfig & SetupGacelaInterface classes
  src/Framework/Bootstrap/AbstractSetupGacela.php
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
Labels: documentation

#212 Remove the profiler feature
  CHANGELOG.md
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/Cache/ProfiledCache.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/ClassResolver/Profiler/AbstractJsonFileProfiler.php
  src/Framework/ClassResolver/Profiler/ClassNameJsonProfiler.php
  src/Framework/ClassResolver/Profiler/CustomServicesJsonProfiler.php
  src/Framework/ClassResolver/Profiler/FileProfilerInterface.php
  src/Framework/ClassResolver/Profiler/GacelaProfiler.php
  src/Framework/Config/Config.php
  src/Framework/DocBlockResolver/DocBlockResolver.php
  src/Framework/Gacela.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/FileProfilerBench.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleA/ConfigA.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleA/DepProvA.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleA/Facade.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleA/FactoryA.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleA/Repository.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleB/ConfigB.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleB/DepProvB.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleB/Facade.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleB/FactoryB.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleB/Repository.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleC/ConfigC.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleC/DepProvC.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleC/Facade.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleC/FactoryC.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleC/Repository.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleD/ConfigD.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleD/DepProvD.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleD/Facade.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleD/FactoryD.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleD/Repository.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleE/ConfigE.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleE/DepProvE.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleE/Facade.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleE/FactoryE.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleE/Repository.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleF/Config.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleF/DependencyProvider.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleF/Facade.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleF/Factory.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleF/Repository.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleG/Config.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleG/DependencyProvider.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleG/Facade.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleG/Factory.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/ModuleG/Repository.php
  tests/Benchmark/Framework/ClassResolver/FileProfiler/config/default.php
  tests/Feature/Framework/GacelaProfiler/FileProfilerFeatureTest.php
  tests/Feature/Framework/GacelaProfiler/Module/Facade.php
  tests/Feature/Framework/GacelaProfiler/Module/Factory.php
  tests/Feature/Framework/GacelaProfiler/Module/Persistence/FakeRepository.php
  tests/Unit/Framework/ClassResolver/Profiler/GacelaProfilerTest.php
Labels: enhancement

#215 Adding an event listeners system
  CHANGELOG.md
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/ClassInfo.php
  src/Framework/ClassResolver/ClassInfoInterface.php
  src/Framework/Config/Config.php
  src/Framework/EventListener/AbstractGacelaEvent.php
  src/Framework/EventListener/ClassResolver/GacelaClassResolverListener.php
  src/Framework/EventListener/ClassResolver/ResolvedClassCachedEvent.php
  src/Framework/EventListener/ClassResolver/ResolvedClassCreatedEvent.php
  src/Framework/EventListener/ClassResolver/ResolvedClassTriedFromParentEvent.php
  src/Framework/EventListener/ClassResolver/ResolvedCreatedDefaultClassEvent.php
  src/Framework/EventListener/EventDispatcher.php
  src/Framework/EventListener/EventDispatcherInterface.php
  src/Framework/EventListener/GacelaEventInterface.php
  src/Framework/EventListener/GacelaListenerInterface.php
  src/Framework/EventListener/NullEventDispatcher.php
  tests/Feature/Framework/ListeningEvents/DisableListenersTest.php
  tests/Feature/Framework/ListeningEvents/GacelaClassResolverListenerTest.php
  tests/Feature/Framework/ListeningEvents/Module/Facade.php
  tests/Feature/Framework/ListeningEvents/Module/Factory.php
Labels: enhancement

#216 Add ConfigReaderEvents
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Config/ConfigReader/PhpConfigReader.php
  src/Framework/EventListener/AbstractGacelaEvent.php
  src/Framework/EventListener/ClassResolver/AbstractGacelaClassResolverEvent.php
  src/Framework/EventListener/ClassResolver/GacelaClassResolverListener.php
  src/Framework/EventListener/ClassResolver/ResolvedClassCachedEvent.php
  src/Framework/EventListener/ClassResolver/ResolvedClassCreatedEvent.php
  src/Framework/EventListener/ClassResolver/ResolvedClassTriedFromParentEvent.php
  src/Framework/EventListener/ClassResolver/ResolvedCreatedDefaultClassEvent.php
  src/Framework/EventListener/ConfigReader/GacelaConfigReaderListener.php
  src/Framework/EventListener/ConfigReader/ReadPhpConfigEvent.php
  src/Framework/EventListener/GacelaEventInterface.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/DisableListenersTest.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverListenerTest.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/Module/Facade.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/Module/Factory.php
  tests/Feature/Framework/ListeningEvents/ConfigReader/GacelaConfigReaderListenerTest.php
  tests/Feature/Framework/ListeningEvents/ConfigReader/config/default.php
  tests/Feature/Framework/ListeningEvents/ConfigReader/config/local.php
Labels: enhancement
