Repository gacela-project/gacela, pull requests merged in 2022-11, with the labels that each got.

#217 Add GacelaConfig::registerGenericListener()
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/EventListener/EventDispatcher.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/DisableListenersTest.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverGeneralListenerTest.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverSpecificListenerTest.php
  tests/Feature/Framework/ListeningEvents/ConfigReader/GacelaConfigReaderListenerTest.php
Labels: enhancement

#218 Add Config::createWithSetup()
  src/Framework/AbstractConfig.php
  src/Framework/Config/Config.php
  src/Framework/Gacela.php
  tests/Benchmark/Framework/ClassResolver/AnonymousGlobal/AnonymousGlobalsBench.php
Labels: refactoring

#219 Added File and InMemory *CacheCreatedEvent
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/EventListener/ClassResolver/Cache/ClassNamePhpCacheCreatedEvent.php
  src/Framework/EventListener/ClassResolver/Cache/InMemoryCacheCreatedEvent.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/DisableListenersTest.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverGeneralListenerTest.php
  tests/Integration/Framework/GlobalServices/AnonymousClassesTest.php
Labels: enhancement

#220 Rename Event directory
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/Config/Config.php
  src/Framework/Config/ConfigReader/PhpConfigReader.php
  src/Framework/Event/ClassResolver/AbstractGacelaClassResolverEvent.php
  src/Framework/Event/ClassResolver/Cache/ClassNamePhpCacheCreatedEvent.php
  src/Framework/Event/ClassResolver/Cache/InMemoryCacheCreatedEvent.php
  src/Framework/Event/ClassResolver/ResolvedClassCachedEvent.php
  src/Framework/Event/ClassResolver/ResolvedClassCreatedEvent.php
  src/Framework/Event/ClassResolver/ResolvedClassTriedFromParentEvent.php
  src/Framework/Event/ClassResolver/ResolvedCreatedDefaultClassEvent.php
  src/Framework/Event/ConfigReader/ReadPhpConfigEvent.php
  src/Framework/Event/Dispatcher/ConfigurableEventDispatcher.php
  src/Framework/Event/Dispatcher/EventDispatcherInterface.php
  src/Framework/Event/Dispatcher/NullEventDispatcher.php
  src/Framework/Event/GacelaEventInterface.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverGeneralListenerTest.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverSpecificListenerTest.php
  tests/Feature/Framework/ListeningEvents/ConfigReader/ReadPhpConfigEventTest.php
Labels: refactoring

#221 Refactor dispatchEvent into EventDispatchingCapabilities trait
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/Config/ConfigReader/PhpConfigReader.php
  src/Framework/Event/Dispatcher/EventDispatchingCapabilities.php
Labels: refactoring

#223 Make static the ClassNameFinder
  src/Framework/ClassResolver/AbstractClassResolver.php
  tests/Feature/Framework/ResolveDifferentProjectNamespaces/FeatureTest.php
  tests/Feature/Framework/UsingCustomSuffixTypes/FeatureTest.php
Labels: refactoring

#224 Add ClassNameFinder events
  src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
  src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameCachedFoundEvent.php
  src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameInvalidCandidateFoundEvent.php
  src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameNotFoundEvent.php
  src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameValidCandidateFoundEvent.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverGeneralListenerTest.php
Labels: enhancement

#225 Combine and override different SetupGacela objects
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactory.php
  src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php
  tests/Unit/Framework/Bootstrap/SetupGacelaTest.php
Labels: enhancement

#226 Fix PhpFileCache
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/Cache/AbstractPhpFileCache.php
  src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
  src/Framework/ClassResolver/ClassResolverCache.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/Config/ConfigReader/PhpConfigReader.php
  src/Framework/DocBlockResolver/DocBlockResolver.php
  src/Framework/DocBlockResolver/DocBlockResolverCache.php
  src/Framework/Event/ClassResolver/Cache/ClassNameCacheCachedEvent.php
  src/Framework/Event/ClassResolver/Cache/ClassNameInMemoryCacheCreatedEvent.php
  src/Framework/Event/ClassResolver/Cache/CustomServicesCacheCachedEvent.php
  src/Framework/Event/ClassResolver/Cache/CustomServicesInMemoryCacheCreatedEvent.php
  src/Framework/Event/ClassResolver/Cache/CustomServicesPhpCacheCreatedEvent.php
  src/Framework/Event/Dispatcher/EventDispatchingCapabilities.php
  src/Framework/Gacela.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverGeneralListenerTest.php
  tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverCustomServicesAwareTest.php
  tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverInMemoryAwareTest.php
Labels: bug

#227 Optimize DocBlockResolver resolvableType
  src/Framework/DocBlockResolver/DocBlockResolvable.php
  src/Framework/DocBlockResolver/DocBlockResolver.php
  tests/Integration/Framework/DocBlockResolver/DocBlockResolverTest.php
  tests/Integration/Framework/DocBlockResolver/Module/FakeCommand.php
  tests/Integration/Framework/DocBlockResolver/Module/FakeConfig.php
  tests/Integration/Framework/DocBlockResolver/Module/FakeFacade.php
  tests/Integration/Framework/DocBlockResolver/Module/FakeFactory.php
  tests/Integration/Framework/DocBlockResolver/Module/FakeRandomService.php
Labels: refactoring

#228 Fixing DocBlockResolverAwareTrait cache
  src/Framework/DocBlockResolverAwareTrait.php
Labels: bug

#230 Change to protected AbstractClassResolver->doResolve()
  src/Framework/ClassResolver/AbstractClassResolver.php
Labels: enhancement

#229 Add container factory method
  src/Framework/Container/Container.php
  src/Framework/Container/Exception/ContainerException.php
  tests/Unit/Framework/Container/ContainerTest.php
Labels: enhancement

#232 Remove useless ContainerException::notFound()
  src/Framework/Container/Exception/ContainerException.php
Labels: refactoring

#234 Frozen used Container services
  src/Framework/Container/Container.php
  src/Framework/Container/Exception/ContainerException.php
  tests/Unit/Framework/Container/ContainerTest.php
Labels: enhancement

#235 Remove $raw array from container
  src/Framework/Container/Container.php
Labels: enhancement

#236 Add Container::protect()
  CHANGELOG.md
  src/Framework/Container/Container.php
  src/Framework/Container/Exception/ContainerException.php
  tests/Unit/Framework/Container/ContainerTest.php
Labels: enhancement
