Repository gacela-project/gacela, pull requests merged in 2022-07, with the labels that each got.

#179 Resolve different project namespaces
  CHANGELOG.md
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/ClassInfo.php
  src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleInterface.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithModulePrefix.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithoutModulePrefix.php
  src/Framework/ClassResolver/ClassResolverExceptionTrait.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/Config/Config.php
  src/Framework/Container/Exception/ContainerKeyNotFoundException.php
  tests/Feature/Framework/ResolveDifferentProjectNamespaces/FeatureTest.php
  tests/Feature/Framework/ResolveDifferentProjectNamespaces/config/default.php
  tests/Feature/Framework/ResolveDifferentProjectNamespaces/src/Main/ModuleA/Factory.php
  tests/Feature/Framework/ResolveDifferentProjectNamespaces/src/Secondary/ModuleB/Factory.php
  tests/Feature/Framework/ResolveDifferentProjectNamespaces/vendor/ThirdParty/ModuleA/Facade.php
  tests/Feature/Framework/ResolveDifferentProjectNamespaces/vendor/ThirdParty/ModuleA/Factory.php
  tests/Feature/Framework/ResolveDifferentProjectNamespaces/vendor/ThirdParty/ModuleB/Facade.php
  tests/Feature/Framework/ResolveDifferentProjectNamespaces/vendor/ThirdParty/ModuleB/Factory.php
  tests/Unit/Framework/ClassResolver/ClassInfoTest.php
  tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
Labels: enhancement

#181 Load both gacela.php and gacela-xxx.php files
  src/Framework/Config/ConfigFactory.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/FeatureTest.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/LocalConfig/Config.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/config/default.php
Labels: enhancement

#180 Gacela configuration for different environments
  CHANGELOG.md
  src/Framework/Config/ConfigFactory.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/FeatureTest.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/LocalConfig/Config.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/LocalConfig/Facade.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/LocalConfig/Factory.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/config/default.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/config/dev.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/config/prod.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/gacela-dev.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/gacela-prod.php
  tests/Feature/Framework/UsingGacelaFileFromCustomEnv/gacela.php
Labels: enhancement

#184 Create addAppConfigKeyValues() from GacelaConfig
  CHANGELOG.md
  composer.json
  src/Framework/Bootstrap/GacelaConfig.php
  tests/Feature/Framework/AddAppConfigKeyValuesInGacelaBootstrap/FeatureTest.php
  tests/Feature/Framework/AddAppConfigKeyValuesInGacelaBootstrap/Module/Config.php
  tests/Feature/Framework/AddAppConfigKeyValuesInGacelaBootstrap/Module/Facade.php
  tests/Feature/Framework/AddAppConfigKeyValuesInGacelaBootstrap/Module/Factory.php
Labels: enhancement

#186 Fixing setCacheEnable behaviour
  CHANGELOG.md
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/Cache/GacelaCache.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/Config/Config.php
  src/Framework/Config/ConfigInterface.php
  src/Framework/DocBlockResolverAwareTrait.php
  tests/Feature/Framework/CustomCacheDirectory/FileCacheFeatureTest.php
  tests/Feature/Framework/CustomNoCacheDirectory/Module/Facade.php
  tests/Feature/Framework/CustomNoCacheDirectory/Module/Persistence/FakeRepository.php
  tests/Feature/Framework/CustomNoCacheDirectory/NoFileCacheFeatureTest.php
  tests/Feature/Framework/GacelaConfigAddAppConfigKeyValues/FeatureTest.php
  tests/Feature/Framework/GacelaConfigAddAppConfigKeyValues/Module/Config.php
  tests/Feature/Framework/GacelaConfigAddAppConfigKeyValues/Module/Facade.php
  tests/Feature/Framework/GacelaConfigAddAppConfigKeyValues/Module/Factory.php
  tests/Unit/Framework/ClassResolver/Cache/GacelaCacheTest.php
Labels: bug

#187 Add "psalm/plugin-phpunit" + update dependencies
  composer.json
  psalm.xml
Labels: dependencies

#188 Extract class refactoring in DocBlockResolverAwareTrait
  src/Framework/DocBlockResolver/DocBlockResolvable.php
  src/Framework/DocBlockResolver/DocBlockResolver.php
  src/Framework/DocBlockResolverAwareTrait.php
Labels: refactoring
