Repository gacela-project/gacela, pull requests merged in 2022-06, with the labels that each got.

#164 Doc block resolver aware with no parent
  src/Framework/DocBlockResolverAwareTrait.php
  tests/Integration/Framework/DocBlockResolverAware/BadDummyDocBlockResolverAware.php
  tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverAwareTest.php
Labels: bug

#165 Cache class names and resolvable types
  CHANGELOG.md
  composer.json
  src/Framework/ClassResolver/ClassNameCache.php
  src/Framework/ClassResolver/ClassNameCacheInterface.php
  src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
  src/Framework/ClassResolver/ClassResolverExceptionTrait.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/Gacela.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ClassNameCacheBench.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleA/ConfigA.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleA/DepProvA.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleA/Facade.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleA/FactoryA.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleB/ConfigB.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleB/DepProvB.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleB/Facade.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleB/FactoryB.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleC/ConfigC.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleC/DepProvC.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleC/Facade.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleC/FactoryC.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleD/ConfigD.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleD/DepProvD.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleD/Facade.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleD/FactoryD.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleE/ConfigE.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleE/DepProvE.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleE/Facade.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleE/FactoryE.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleF/Config.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleF/DependencyProvider.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleF/Facade.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleF/Factory.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleG/Config.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleG/DependencyProvider.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleG/Facade.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ModuleG/Factory.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/config/default.php
  tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
  tests/Unit/Framework/ClassResolver/InMemoryClassNameCache.php
Labels: enhancement

#167 Rename $config->resetCache() to $config->setCacheEnabled()
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  src/Framework/Gacela.php
  tests/Benchmark/Framework/ClassResolver/ClassNameCache/ClassNameCacheBench.php
  tests/Integration/Framework/Config/ConfigTest.php
  tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
Labels: refactoring

#170 Refactor SetupGacela
  composer.lock
  src/Framework/Bootstrap/SetupGacela.php
Labels: refactoring

#171 Group gacela cache files inside a cache directory
  src/Framework/ClassResolver/AbstractFileCache.php
  src/Framework/ClassResolver/Cache/GacelaCache.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/ClassResolver/InMemoryCache.php
  src/Framework/Config/Config.php
  src/Framework/DocBlockResolverAwareTrait.php
  tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverCustomServicesAwareTest.php
  tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverInMemoryAwareTest.php
  tests/Integration/Framework/DocBlockResolverAware/config/custom-services/default.php
  tests/Integration/Framework/DocBlockResolverAware/config/in-memory/default.php
  tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
Labels: enhancement

#173 Add .editorconfig & .gitattributes files
  .editorconfig
  .gitattributes
  README.md
Labels: enhancement

#174 Allow defining custom cache directory name
  CHANGELOG.md
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  src/Framework/Config/Config.php
  tests/Feature/CodeGenerator/MakeFileCommandTest.php
  tests/Feature/CodeGenerator/MakeModuleCommandTest.php
  tests/Feature/Framework/CustomCacheDirectory/FeatureTest.php
  tests/Feature/Framework/CustomCacheDirectory/Module/Facade.php
  tests/Feature/Framework/CustomCacheDirectory/Module/Persistence/FakeRepository.php
  tests/Feature/Util/DirectoryUtil.php
Labels: enhancement

#175 Fix setCacheDirectory() with nested dir levels
  CHANGELOG.md
  src/Framework/ClassResolver/AbstractFileCache.php
  tests/Feature/Framework/CustomCacheDirectory/FeatureTest.php
Labels: bug

#176 Refactor gacela cache default values
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/ClassResolver/Cache/GacelaCache.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/DocBlockResolverAwareTrait.php
  tests/Integration/Framework/DocBlockResolverAware/config/custom-services/default.php
  tests/Integration/Framework/DocBlockResolverAware/config/in-memory/default.php
Labels: refactoring

#177 Change cache default directory to .gacela/cache
  src/Framework/ClassResolver/Cache/GacelaCache.php
Labels: enhancement
