Repository gacela-project/gacela, pull requests merged in 2022-01, with the labels that each got.

#66 Remove deprecated gacela config as array
  src/Framework/Config/ConfigFactory.php
  src/Framework/Config/ConfigGacelaMapper.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigItem.php
  tests/Integration/Framework/UsingDeprecatedArrayConfig/IntegrationTest.php
  tests/Integration/Framework/UsingDeprecatedArrayConfig/LocalConfig/Domain/GreeterGeneratorInterface.php
  tests/Integration/Framework/UsingDeprecatedArrayConfig/LocalConfig/Domain/NumberGeneratorInterface.php
  tests/Integration/Framework/UsingDeprecatedArrayConfig/LocalConfig/Domain/NumberService.php
  tests/Integration/Framework/UsingDeprecatedArrayConfig/LocalConfig/Facade.php
  tests/Integration/Framework/UsingDeprecatedArrayConfig/LocalConfig/Factory.php
  tests/Integration/Framework/UsingDeprecatedArrayConfig/LocalConfig/Infrastructure/CustomCompanyGenerator.php
  tests/Integration/Framework/UsingDeprecatedArrayConfig/LocalConfig/Infrastructure/CustomNameGenerator.php
  tests/Integration/Framework/UsingDeprecatedArrayConfig/gacela.php
  tests/Unit/Framework/Config/ConfigInitTest.php
Labels: refactoring

#67 Ensure that Gacela is compatible with PHP 8.1
  .github/workflows/ci.yml
Labels: enhancement

#69 Refactor CodeGenerator feature tests.
  tests/Feature/CodeGenerator/MakeFileCommandTest.php
  tests/Feature/CodeGenerator/MakeModuleCommandTest.php
Labels: refactoring, pure testing

#68 Add phpbench tests for a normal module
  phpbench.json
  tests/Benchmark/Framework/ClassResolver/AnonymousGlobal/AnonymousGlobalsBench.php
  tests/Benchmark/Framework/ClassResolver/NormalModule/Domain/DomainClass.php
  tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleBench.php
  tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleConfig.php
  tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleDependencyProvider.php
  tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleFacade.php
  tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleFactory.php
Labels: pure testing

#70 Allow null as default config value
  src/Framework/AbstractConfig.php
  src/Framework/Config.php
  tests/Integration/Framework/UsingConfigWithDefaultValues/IntegrationTest.php
  tests/Integration/Framework/UsingConfigWithDefaultValues/LocalConfig/Config.php
  tests/Unit/Framework/ConfigTest.php
Labels: enhancement

#71 Minor clean up and test improvement
  src/Framework/Config.php
  src/Framework/Config/ConfigInit.php
  tests/Integration/Framework/UsingConfigTypePhp/IntegrationTest.php
  tests/Integration/Framework/UsingConfigTypePhp/LocalConfig/Config.php
  tests/Integration/Framework/UsingConfigTypePhp/config/default.php
  tests/Integration/Framework/UsingConfigTypePhp/config/local.php
  tests/Integration/Framework/UsingConfigTypePhp/config/override.php
Labels: refactoring

#72 Global services as param on mapping interfaces
  CHANGELOG.md
  src/Framework/AbstractConfigGacela.php
  src/Framework/Config/ConfigInit.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
  tests/Integration/Framework/BindingInterfacesInGacelaConfigFile/gacela.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Domain/Greeter/CorrectCompanyGenerator.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Domain/Greeter/CustomNameGenerator.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Domain/Greeter/IncorrectCompanyGenerator.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Domain/GreeterService.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Domain/NumberService.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Facade.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Factory.php
  tests/Integration/Framework/BindingInterfacesWithInnerDependencies/gacela.php
  tests/Unit/Framework/Config/ConfigInitTest.php
Labels: enhancement

#74 Add homepage to composer.json
  composer.json
Labels: documentation

#76 Rename ConfigInit
  CHANGELOG.md
  src/CodeGenerator/CodeGeneratorConfig.php
  src/CodeGenerator/Domain/CommandArguments/CommandArgumentsParser.php
  src/Framework/AbstractConfig.php
  src/Framework/AbstractFacade.php
  src/Framework/AbstractFactory.php
  src/Framework/Config.php
  src/Framework/Config/ConfigFactory.php
  src/Framework/Config/ConfigLoader.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigItem.php
  src/Framework/Exception/Backtrace.php
  src/Framework/Gacela.php
  tests/Unit/Framework/Config/ConfigInitTest.php
Labels: refactoring

#77 Add unit tests for Backtrace
  src/Framework/ClassResolver/ClassResolverExceptionTrait.php
  src/Framework/Exception/Backtrace.php
  tests/Unit/Framework/Exception/BacktraceTest.php
Labels: refactoring, pure testing
