Repository gacela-project/gacela, pull requests merged in 2022-02, with the labels that each got.

#78 Update Config file
  CHANGELOG.md
  composer.json
  composer.lock
  src/Framework/Config.php
  src/Framework/Gacela.php
  tests/Integration/Framework/UsingConfigTypeEnv/IntegrationTest.php
  tests/Integration/Framework/UsingConfigTypeEnv/LocalConfig/Config.php
  tests/Integration/Framework/UsingConfigTypeEnv/LocalConfig/Facade.php
  tests/Integration/Framework/UsingConfigTypeEnv/LocalConfig/Factory.php
  tests/Integration/Framework/UsingConfigTypeEnv/config/.env.dist
  tests/Integration/Framework/UsingConfigTypeEnv/config/.env.local.dist
  tests/Integration/Framework/UsingConfigTypeEnv/config/omit.php
  tests/Integration/Framework/UsingConfigTypeEnv/config/omit.yml
  tests/Integration/Framework/UsingConfigTypeEnv/gacela.php
  tests/Integration/Framework/UsingMultipleConfig/IntegrationTest.php
  tests/Integration/Framework/UsingMultipleConfig/LocalConfig/Domain/SimpleEnvConfigReader.php
  tests/Integration/Framework/UsingMultipleConfig/gacela.php
  tests/Unit/Framework/ConfigTest.php
Labels: refactoring

#79 Move config-readers as globalServices and gacela.php
  CHANGELOG.md
  src/Framework/AbstractConfigGacela.php
  src/Framework/Config.php
  src/Framework/Config/ConfigLoader.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
  src/Framework/Gacela.php
  tests/Integration/Framework/UsingMultipleConfig/IntegrationTest.php
  tests/Unit/Framework/Config/ConfigInitTest.php
  tests/Unit/Framework/ConfigTest.php
Labels: refactoring

#81 Allow using config from custom env
  CHANGELOG.md
  src/Framework/Config.php
  src/Framework/Config/ConfigFactory.php
  src/Framework/Config/ConfigLoader.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/PathNormalizer/AbsolutePathNormalizer.php
  src/Framework/Config/PathNormalizer/AbsolutePathStrategyInterface.php
  src/Framework/Config/PathNormalizer/NoEnvAbsolutePathStrategy.php
  src/Framework/Config/PathNormalizer/SuffixAbsolutePathStrategy.php
  src/Framework/Config/PathNormalizerInterface.php
  tests/Integration/Framework/UsingConfigFromCustomEnv/IntegrationTest.php
  tests/Integration/Framework/UsingConfigFromCustomEnv/LocalConfig/Config.php
  tests/Integration/Framework/UsingConfigFromCustomEnv/LocalConfig/Facade.php
  tests/Integration/Framework/UsingConfigFromCustomEnv/LocalConfig/Factory.php
  tests/Integration/Framework/UsingConfigFromCustomEnv/config/default-dev.php
  tests/Integration/Framework/UsingConfigFromCustomEnv/config/default-prod.php
  tests/Integration/Framework/UsingConfigFromCustomEnv/config/default.php
  tests/Integration/Framework/UsingConfigFromCustomEnv/config/local.php
  tests/Unit/Framework/Config/ConfigInitTest.php
  tests/Unit/Framework/Config/PathNormalizer/NoEnvAbsolutePathStrategyTest.php
  tests/Unit/Framework/Config/PathNormalizer/SuffixAbsolutePathStrategyTest.php
Labels: enhancement

#82 Remove unnecesary type key from config
  src/Framework/Config/ConfigGacelaMapper.php
  src/Framework/Config/ConfigLoader.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigItem.php
  tests/Integration/Framework/Config/ConfigTest.php
  tests/Integration/Framework/UsingConfigTypePhp/gacela.php
  tests/Integration/Framework/UsingConfigWithBootstrapSetup/IntegrationTest.php
  tests/Integration/Framework/UsingMultipleConfig/IntegrationTest.php
Labels: refactoring

#85 Add phpmetrics dependency
  composer.json
  composer.lock
Labels: enhancement

#89 Add documentation to AbstractConfigGacela class
  src/Framework/AbstractConfigGacela.php
  src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
  src/Framework/ClassResolver/CustomService/CustomServiceNotValidException.php
  src/Framework/ClassResolver/CustomService/CustomServiceResolver.php
  tests/Feature/Framework/CustomServices/CustomModule/Application/Greeter.php
  tests/Feature/Framework/CustomServices/CustomModule/Facade.php
  tests/Feature/Framework/CustomServices/CustomModule/Factory.php
  tests/Feature/Framework/CustomServices/CustomModule/Infrastructure/Persistence/EntityManager.php
  tests/Feature/Framework/CustomServices/CustomModule/Infrastructure/Persistence/Repository.php
  tests/Feature/Framework/CustomServices/FeatureTest.php
Labels: documentation

#90 Rename custom-service-paths to custom-services-location
  CHANGELOG.md
  src/Framework/AbstractConfigGacela.php
  src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
  tests/Feature/Framework/CustomServices/FeatureTest.php
Labels: enhancement

#91 Custom services must implement CustomServiceInterface
  CHANGELOG.md
  src/Framework/AbstractCustomService.php
  src/Framework/ClassResolver/CustomService/CustomServiceNotValidException.php
  src/Framework/ClassResolver/CustomService/CustomServiceResolver.php
  src/Framework/CustomServiceAwareTrait.php
  src/Framework/CustomServiceInterface.php
  tests/Feature/Framework/CustomServices/CustomModule/Application/InvalidGreeter.php
  tests/Feature/Framework/CustomServices/CustomModule/Application/ValidGreeter.php
  tests/Feature/Framework/CustomServices/CustomModule/Facade.php
  tests/Feature/Framework/CustomServices/FeatureTest.php
Labels: enhancement

#92 Add cachedClassNames for ClassNameFinder
  src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
  src/Framework/CustomServiceAwareTrait.php
  tests/Feature/Framework/CustomServicesLevel/CustomModule/Config.php
  tests/Feature/Framework/CustomServicesLevel/CustomModule/Facade.php
  tests/Feature/Framework/CustomServicesLevel/CustomModule/Level1/Level2/Level3/Level4/CheersService4.php
  tests/Feature/Framework/CustomServicesLevel/CustomModule/Level1/Level2/Level3/Level4/GreetService4.php
  tests/Feature/Framework/CustomServicesLevel/FeatureTest.php
  tests/Feature/Framework/CustomServicesLevel/config/default.php
Labels: enhancement

#97 Remove CustomService feature
  CHANGELOG.md
  src/Framework/AbstractConfigGacela.php
  src/Framework/AbstractCustomService.php
  src/Framework/AbstractFacade.php
  src/Framework/AbstractFactory.php
  src/Framework/ClassResolver/AbstractClassResolver.php
  src/Framework/ClassResolver/ClassInfo.php
  src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleInterface.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithModulePrefix.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithoutModulePrefix.php
  src/Framework/ClassResolver/ClassResolverFactory.php
  src/Framework/ClassResolver/CustomService/CustomServiceNotFoundException.php
  src/Framework/ClassResolver/CustomService/CustomServiceNotValidException.php
  src/Framework/ClassResolver/CustomService/CustomServiceResolver.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
  src/Framework/CustomServiceAwareTrait.php
  src/Framework/CustomServiceInterface.php
  tests/Feature/Framework/CustomServices/CustomModule/Application/Factory.php
  tests/Feature/Framework/CustomServices/CustomModule/Application/InvalidGreeter.php
  tests/Feature/Framework/CustomServices/CustomModule/Application/Repository.php
  tests/Feature/Framework/CustomServices/CustomModule/Application/ValidGreeter.php
  tests/Feature/Framework/CustomServices/CustomModule/Config.php
  tests/Feature/Framework/CustomServices/CustomModule/Facade.php
  tests/Feature/Framework/CustomServices/CustomModule/Factory.php
  tests/Feature/Framework/CustomServices/CustomModule/Infrastructure/Factory.php
  tests/Feature/Framework/CustomServices/CustomModule/Infrastructure/Persistence/EntityManager.php
  tests/Feature/Framework/CustomServices/CustomModule/Infrastructure/Persistence/Repository.php
  tests/Feature/Framework/CustomServices/FeatureTest.php
  tests/Feature/Framework/CustomServices/config/default.php
  tests/Feature/Framework/CustomServicesLevel/CustomModule/Config.php
  tests/Feature/Framework/CustomServicesLevel/CustomModule/Facade.php
  tests/Feature/Framework/CustomServicesLevel/CustomModule/Level1/Level2/Level3/Level4/CheersService4.php
  tests/Feature/Framework/CustomServicesLevel/CustomModule/Level1/Level2/Level3/Level4/GreetService4.php
  tests/Feature/Framework/CustomServicesLevel/FeatureTest.php
  tests/Feature/Framework/CustomServicesLevel/config/default.php
Labels: enhancement

#98 Remove deprecated appRootDir methods from Config
  CHANGELOG.md
  src/Framework/Config.php
  tests/Feature/Framework/RemoveKeyFromContainer/FeatureTest.php
Labels: enhancement

#102 Move ConfigReader next to the config path
  CHANGELOG.md
  composer.json
  src/Framework/AbstractConfigGacela.php
  src/Framework/Config/ConfigFactory.php
  src/Framework/Config/ConfigGacelaMapper.php
  src/Framework/Config/ConfigLoader.php
  src/Framework/Config/ConfigReader/PhpConfigReader.php
  src/Framework/Config/ConfigReaderInterface.php
  src/Framework/Config/GacelaConfigFileFactory.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigItem.php
  src/Framework/Config/PathNormalizer/AbsolutePathNormalizer.php
  src/Framework/Config/PathNormalizer/WithSuffixAbsolutePathStrategy.php
  src/Framework/Config/PathNormalizer/WithoutSuffixAbsolutePathStrategy.php
  src/Framework/Exception/Backtrace.php
  tests/Feature/Framework/UsingConfigFromCustomEnv/FeatureTest.php
  tests/Feature/Framework/UsingMultipleConfig/FeatureTest.php
  tests/Feature/Framework/UsingMultipleConfig/LocalConfig/Config.php
  tests/Feature/Framework/UsingMultipleConfig/LocalConfig/Domain/SimpleEnvConfigReader.php
  tests/Feature/Framework/UsingMultipleConfig/config/local.php
  tests/Integration/Framework/Config/ConfigTest.php
  tests/Unit/Framework/Config/ConfigInitTest.php
  tests/Unit/Framework/Config/PathNormalizer/SuffixAbsolutePathStrategyTest.php
  tests/Unit/Framework/Config/PathNormalizer/WithSuffixAbsolutePathStrategyTest.php
  tests/Unit/Framework/Config/PathNormalizer/WithoutSuffixAbsolutePathStrategyTest.php
Labels: enhancement
