Repository gacela-project/gacela, pull requests merged in 2023-05, with the labels that each got.

#272 Rename addPlugin() to addAfterPlugin()
  CHANGELOG.md
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupCombinator.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  src/Framework/Gacela.php
  tests/Feature/Framework/Plugins/AfterFeatureTest.php
  tests/Unit/Framework/Bootstrap/SetupGacelaTest.php
Labels: refactoring

#274 Add extend config
  CHANGELOG.md
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupCombinator.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  src/Framework/Gacela.php
  src/Framework/Plugin/PluginInterface.php
  tests/Feature/Framework/ExtendConfig/FeatureTest.php
  tests/Feature/Framework/ExtendConfig/Module/Infrastructure/BindingStringValue.php
  tests/Feature/Framework/Plugins/FeatureTest.php
  tests/Feature/Framework/Plugins/Module/Infrastructure/ExamplePluginWithConstructor.php
  tests/Feature/Framework/Plugins/Module/Infrastructure/ExamplePluginWithoutConstructor.php
  tests/Unit/Framework/Bootstrap/SetupGacelaTest.php
Labels: enhancement

#275 Remove deprecated setFileCacheEnabled() & setFileCacheDirectory()
  CHANGELOG.md
  src/Framework/Bootstrap/GacelaConfig.php
Labels: enhancement

#276 Add Gacela::rootDir()
  CHANGELOG.md
  src/Framework/Gacela.php
  tests/Integration/Framework/GacelaTest.php
Labels: enhancement

#277 Allow plugins as callables
  composer.json
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  src/Framework/Gacela.php
  tests/Feature/Framework/Plugins/FeatureTest.php
Labels: enhancement

#279 Refactor setup event dispatcher
  src/Framework/Bootstrap/SetupCombinator.php
  src/Framework/Bootstrap/SetupEventDispatcher.php
  src/Framework/Bootstrap/SetupGacela.php
Labels: refactoring

#280 Rename internal ConfigBuilder to AppConfigBuilder
  src/Framework/Bootstrap/AbstractSetupGacela.php
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  src/Framework/Config/GacelaConfigBuilder/AppConfigBuilder.php
  src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactory.php
  src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php
  tests/Integration/Framework/Config/ConfigFactory/ConfigFactoryTest.php
  tests/Unit/Framework/Config/GacelaConfigBuilder/ConfigBuilderTest.php
  tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactoryTest.php
Labels: refactoring

#281 Rename method to extendGacelaConfig()
  CHANGELOG.md
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupCombinator.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Bootstrap/SetupGacelaInterface.php
  tests/Feature/Framework/ExtendConfig/FeatureTest.php
Labels: refactoring

#282 Add GacelaConfig::enableFileCache()
  src/Framework/Bootstrap/GacelaConfig.php
  tests/Feature/Framework/FileCache/FileCacheFeatureTest.php
Labels: enhancement

#283 Test autoload plugin invoke args
  tests/Feature/Framework/Plugins/FeatureTest.php
  tests/Feature/Framework/Plugins/Module/Infrastructure/ExamplePluginWithConstructor.php
  tests/Feature/Framework/Plugins/Module/Infrastructure/ExamplePluginWithInvokeArgs.php
  tests/Feature/Framework/Plugins/Module/Infrastructure/ExamplePluginWithoutConstructor.php
Labels: pure testing

#284 Add command list modules
  src/Console/ConsoleDependencyProvider.php
  src/Console/ConsoleFacade.php
  src/Console/ConsoleFactory.php
  src/Console/Domain/AllAppModules/AllAppModulesFinder.php
  src/Console/Domain/AllAppModules/AppModule.php
  src/Console/Infrastructure/Command/ListModulesCommand.php
  tests/Feature/Console/CodeGenerator/MakeExceptionCommandTest.php
  tests/Feature/Console/CodeGenerator/MakeFileCommandTest.php
  tests/Feature/Console/CodeGenerator/MakeModuleCommandTest.php
  tests/Feature/Console/CodeGenerator/composer.json
  tests/Feature/Console/ListModules/LevelUp/TestModule3/TestModule3Facade.php
  tests/Feature/Console/ListModules/MakeModuleCommandTest.php
  tests/Feature/Console/ListModules/TestModule1/TestModule1Facade.php
  tests/Feature/Console/ListModules/TestModule2/TestModule2Facade.php
  tests/Feature/Console/ListModules/vendor/IgnoreVendorModule/ToBeIgnored.php
  tests/Integration/Console/AllAppModules/Domain/AllAppModulesFinderTest.php
  tests/Integration/Console/AllAppModules/Domain/Module1/IntegrationAppModulesFacade1.php
  tests/Integration/Console/AllAppModules/Domain/Module2/IntegrationAppModulesFacade2.php
  tests/Unit/Console/Domain/AllAppModules/AppModuleTest.php
  tests/Unit/Console/Domain/CommandArguments/CommandArgumentsParserTest.php
  tests/Unit/Console/Domain/FileContent/FileContentGeneratorTest.php
  tests/Unit/Console/Domain/FilenameSanitizer/FilenameSanitizerTest.php
Labels: enhancement

#285 Filter list modules command
  phpstan.neon
  src/Console/ConsoleFacade.php
  src/Console/Domain/AllAppModules/AllAppModulesFinder.php
  src/Console/Infrastructure/Command/ListModulesCommand.php
  tests/Feature/Console/ListModules/FilterListModulesCommandTest.php
  tests/Feature/Console/ListModules/ListModulesCommandTest.php
  tests/Integration/Console/AllAppModules/Domain/AllAppModulesFinderTest.php
Labels: enhancement

#287 Fix: Adjust identifier
  .github/workflows/tests.yml
Labels: bug

#286 Fix: Replace `locked` with `highest` in matrix
  .github/workflows/tests.yml
Labels: bug
