Repository gacela-project/gacela, pull requests merged in 2023-06, with the labels that each got.

#270 Install infection
  .github/workflows/mutation-testing.yml
  .gitignore
  README.md
  composer.json
  composer.lock
  infection.json5
Labels: dependencies

#201 Add full compatibility for windows support
  .github/workflows/tests.yml
  CHANGELOG.md
  phpstan.neon
  src/Console/ConsoleConfig.php
  src/Console/Domain/AllAppModules/AllAppModulesFinder.php
  src/Console/Domain/CommandArguments/CommandArgumentsParser.php
  src/Framework/ClassResolver/ClassInfo.php
  src/Framework/ClassResolver/DocBlockService/DocBlockParser.php
  src/Framework/ClassResolver/DocBlockService/UseBlockParser.php
  tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleBench.php
  tests/Feature/Console/CodeGenerator/MakeModuleCommandTest.php
  tests/Feature/Framework/DocBlockServiceAware/FeatureTest.php
  tests/Integration/Framework/Config/ConfigTest.php
Labels: bug

#293 Improve list modules output
  src/Console/ConsoleFactory.php
  src/Console/Domain/AllAppModules/AllAppModulesFinder.php
  src/Console/Domain/AllAppModules/AppModule.php
  src/Console/Domain/AllAppModules/AppModuleCreator.php
  src/Console/Infrastructure/Command/ListModulesCommand.php
  tests/Feature/Console/ListModules/FilterListModulesCommandTest.php
  tests/Feature/Console/ListModules/LevelUp/TestModule3/TestModule3Config.php
  tests/Feature/Console/ListModules/LevelUp/TestModule3/TestModule3Factory.php
  tests/Feature/Console/ListModules/ListModulesCommandTest.php
  tests/Feature/Console/ListModules/TestModule1/TestModule1DependencyProvider.php
  tests/Feature/Console/ListModules/TestModule1/TestModule1Factory.php
  tests/Integration/Console/AllAppModules/Domain/AllAppModulesFinderTest.php
  tests/Integration/Console/AllAppModules/Domain/AppModuleTest.php
  tests/Integration/Console/AllAppModules/Domain/Module1/Module1Config.php
  tests/Integration/Console/AllAppModules/Domain/Module1/Module1DependencyProvider.php
  tests/Integration/Console/AllAppModules/Domain/Module1/Module1Facade.php
  tests/Integration/Console/AllAppModules/Domain/Module1/Module1Factory.php
  tests/Integration/Console/AllAppModules/Domain/Module2/Module2Facade.php
  tests/Unit/Console/Domain/AllAppModules/AppModuleTest.php
Labels: enhancement

#295 Color list modules command
  CHANGELOG.md
  src/Console/Infrastructure/Command/ListModulesCommand.php
  tests/Feature/Console/ListModules/ListModulesCommandTest.php
Labels: refactoring

#297 Use detailed by default instead of simple
  CHANGELOG.md
  src/Console/Infrastructure/Command/ListModulesCommand.php
  tests/Feature/Console/ListModules/ListModulesCommandTest.php
Labels: refactoring

#298 Change design simple view from gacela list:modules
  CHANGELOG.md
  src/Console/Domain/AllAppModules/AppModule.php
  src/Console/Domain/AllAppModules/AppModuleCreator.php
  src/Console/Infrastructure/Command/ListModulesCommand.php
  tests/Feature/Console/ListModules/ListModulesCommandTest.php
  tests/Integration/Console/AllAppModules/Domain/AllAppModulesFinderTest.php
Labels: refactoring
