Repository gacela-project/gacela, pull requests merged in 2024-08, with the labels that each got.

#313 Install phpstan strict rules
  composer.json
  composer.lock
  phpstan.neon
  src/Console/Domain/AllAppModules/AllAppModulesFinder.php
  src/Console/Domain/FileContent/FileContentGenerator.php
  src/Console/Infrastructure/Command/ListModulesCommand.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/ClassResolver/Cache/AbstractPhpFileCache.php
  src/Framework/ClassResolver/Cache/CacheInterface.php
  src/Framework/ClassResolver/Cache/InMemoryCache.php
  src/Framework/ClassResolver/DocBlockService/DocBlockParser.php
  src/Framework/ClassResolver/DocBlockService/UseBlockParser.php
  src/Framework/ClassResolver/GlobalInstance/AnonymousGlobal.php
  src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
  src/Framework/Container/Locator.php
  src/Framework/DocBlockResolverAwareTrait.php
  src/Framework/FactoryResolverAwareTrait.php
Labels: refactoring

#314 Update dependencies
  composer.json
  composer.lock
  phpstan.neon
  phpunit.xml
  src/Console/ConsoleFactory.php
  src/Console/Domain/AllAppModules/AllAppModulesFinder.php
  src/Console/Domain/CommandArguments/CommandArgumentsException.php
  src/Console/Domain/FileContent/FileContentGenerator.php
  src/Console/Domain/FilenameSanitizer/FilenameSanitizer.php
  src/Console/Infrastructure/Command/MakeFileCommand.php
  src/Console/Infrastructure/Command/MakeModuleCommand.php
  src/Console/Infrastructure/FileContentIo.php
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/ClassResolver/Cache/AbstractPhpFileCache.php
  src/Framework/ClassResolver/ClassInfo.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithModulePrefix.php
  src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithoutModulePrefix.php
  src/Framework/ClassResolver/ClassResolverExceptionTrait.php
  src/Framework/ClassResolver/DocBlockService/UseBlockParser.php
  src/Framework/ClassResolver/GlobalInstance/AnonymousGlobal.php
  src/Framework/ClassResolver/GlobalKey.php
  src/Framework/Config/ConfigFactory.php
  src/Framework/Config/PathNormalizer/WithSuffixAbsolutePathStrategy.php
  src/Framework/Config/PathNormalizer/WithoutSuffixAbsolutePathStrategy.php
  src/Framework/DocBlockResolver/DocBlockResolver.php
  src/Framework/Event/ClassResolver/AbstractGacelaClassResolverEvent.php
  src/Framework/Event/ClassResolver/Cache/ClassNameCacheCachedEvent.php
  src/Framework/Event/ClassResolver/Cache/ClassNameInMemoryCacheCreatedEvent.php
  src/Framework/Event/ClassResolver/Cache/ClassNamePhpCacheCreatedEvent.php
  src/Framework/Event/ClassResolver/Cache/CustomServicesCacheCachedEvent.php
  src/Framework/Event/ClassResolver/Cache/CustomServicesInMemoryCacheCreatedEvent.php
  src/Framework/Event/ClassResolver/Cache/CustomServicesPhpCacheCreatedEvent.php
  src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameCachedFoundEvent.php
  src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameInvalidCandidateFoundEvent.php
  src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameNotFoundEvent.php
  src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameValidCandidateFoundEvent.php
  src/Framework/Event/ConfigReader/ReadPhpConfigEvent.php
  src/Framework/Exception/ConfigException.php
  src/Framework/FactoryResolverAwareTrait.php
  src/Framework/Gacela.php
  tests/Feature/Console/CodeGenerator/MakeFileCommandTest.php
  tests/Feature/Console/CodeGenerator/MakeModuleCommandTest.php
  tests/Feature/Console/ListModules/ListModulesCommandTest.php
  tests/Feature/Framework/BindingInterfacesWithInnerDependencies/LocalConfig/Domain/Greeter/CorrectCompanyGenerator.php
  tests/Feature/Framework/DocBlockServiceAware/Module/Infrastructure/Persistence/FakeDoctrineEntityManager.php
  tests/Feature/Framework/ModuleWithExternalDependencies/Dependent/Service/HelloName.php
  tests/Feature/Framework/ModuleWithExternalDependencies/Supplier/Service/HelloName.php
  tests/Feature/Framework/ModuleWithoutDependencies/WithPrefix/Service/HelloName.php
  tests/Feature/Framework/ModuleWithoutDependencies/WithoutPrefix/Service/HelloName.php
  tests/Fixtures/CustomGacelaConfig.php
  tests/Integration/Framework/GlobalServices/AnonymousClassesTest.php
  tests/Unit/Console/Domain/FilenameSanitizer/FilenameSanitizerTest.php
  tests/Unit/Framework/ClassResolver/GlobalInstance/AnonymousGlobalTest.php
Labels: enhancement, dependencies

#315 Fix disable event listeners
  src/Framework/Bootstrap/SetupGacela.php
  tests/Feature/Framework/ListeningEvents/ClassResolver/DisableListenersTest.php
Labels: bug

#316 Fix flacky feature static facade tests
  tests/Feature/Framework/StaticFacade/FeatureTest.php
Labels: bug

#318 Enable using addGlobal and overrideExistingResolvedClass from Gacela
  CHANGELOG.md
  src/Framework/ClassResolver/GlobalInstance/AnonymousGlobal.php
  src/Framework/Config/Config.php
  src/Framework/Gacela.php
  tests/Feature/Framework/OverrideExistingResolvedClass/FeatureTest.php
  tests/Feature/Framework/OverrideExistingResolvedClass/Module/Config.php
  tests/Feature/Framework/OverrideExistingResolvedClass/Module/Facade.php
  tests/Feature/Framework/OverrideExistingResolvedClass/Module/Factory.php
  tests/Feature/Framework/OverrideExistingResolvedClass/config/default.php
  tests/Unit/Framework/ClassResolver/GlobalInstance/AnonymousGlobalTest.php
Labels: enhancement

#320 Add Module bindings to Provider
  CHANGELOG.md
  src/Framework/AbstractFactory.php
  src/Framework/AbstractProvider.php
  src/Framework/Bootstrap/AbstractSetupGacela.php
  src/Framework/Bootstrap/GacelaConfig.php
  src/Framework/Bootstrap/Setup/GacelaConfigExtender.php
  src/Framework/Bootstrap/Setup/GacelaConfigTransfer.php
  src/Framework/Bootstrap/SetupCombinator.php
  src/Framework/Bootstrap/SetupGacela.php
  src/Framework/Event/ClassResolver/GenericEvent.php
  src/Framework/Gacela.php
  tests/Feature/Framework/BindingsInsideProvider/FeatureTest.php
  tests/Feature/Framework/BindingsInsideProvider/Module/Application/GreeterService.php
  tests/Feature/Framework/BindingsInsideProvider/Module/Domain/Greeter/CompanyGenerator.php
  tests/Feature/Framework/BindingsInsideProvider/Module/Domain/Greeter/Team.php
  tests/Feature/Framework/BindingsInsideProvider/Module/Domain/GreeterGeneratorInterface.php
  tests/Feature/Framework/BindingsInsideProvider/Module/Facade.php
  tests/Feature/Framework/BindingsInsideProvider/Module/Factory.php
  tests/Feature/Framework/BindingsInsideProvider/Module/Provider.php
Labels: enhancement
